-- AlterTable
UPDATE "Course" SET "category" = 'Autre' WHERE "category" IS NULL;
ALTER TABLE "Course" ALTER COLUMN "category" SET NOT NULL;
ALTER TABLE "Course" ADD COLUMN "accessMode" TEXT NOT NULL DEFAULT 'LINEAR';
ALTER TABLE "Course" ADD COLUMN "modules" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Course" ADD COLUMN "quiz" JSONB NOT NULL DEFAULT '[]';
ALTER TABLE "Course" ADD COLUMN "createdAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
ALTER TABLE "Course" ADD COLUMN "updatedAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;

-- AlterTable
ALTER TABLE "Enrollment" ADD COLUMN "completedModuleIds" TEXT[] DEFAULT ARRAY[]::TEXT[];
ALTER TABLE "Enrollment" ADD COLUMN "quizScore" INTEGER;
ALTER TABLE "Enrollment" ADD COLUMN "enrolledAt" TIMESTAMP(3) NOT NULL DEFAULT CURRENT_TIMESTAMP;
